name: "Podcast Generator"
author: "Ray"
description: "Generates a feed for a podcast from a YAML file"
runs: 
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputs:
  email: The committer's email address
    description: true
    default: ${{github.actor}}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{github.actor}}